sudo: required

services:
  - docker

cache:
  directories:
    - vendor/

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

install:
  - docker build travisci/docker/php -t parallel/php:5.6
  - bin/composer install

script:
  - ./travisci/bin/php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./travisci/bin/php vendor/bin/test-reporter
